version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:8080"
  db:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/usr/app/db
    
volumes:
  db-data:
